LOCAL_PATH := /

ifneq ($(call intel-target-need-intel-libraries),)
ifeq ($(ICC_COMPILER_VERSION),13_0)
include $(CLEAR_VARS)
LOCAL_SYSTEM_SHARED_LIBRARIES :=
LOCAL_MODULE := libimf
LOCAL_MODULE_SUFFIX:=.so
LOCAL_STRIP_MODULE:=true
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_SRC_FILES := $(shell env ANDROID_GNU_X86_TOOLCHAIN=$(ANDROID_GNU_X86_TOOLCHAIN) $(TARGET_ICC) -m32 -print-file-name=libimf.so)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_SYSTEM_SHARED_LIBRARIES :=
LOCAL_MODULE := libintlc
LOCAL_MODULE_SUFFIX:=.so
LOCAL_STRIP_MODULE:=true
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_SRC_FILES := $(shell env ANDROID_GNU_X86_TOOLCHAIN=$(ANDROID_GNU_X86_TOOLCHAIN) $(TARGET_ICC) -m32 -print-file-name=libintlc.so)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_SYSTEM_SHARED_LIBRARIES :=
LOCAL_MODULE := libsvml
LOCAL_MODULE_SUFFIX:=.so
LOCAL_STRIP_MODULE:=true
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_SRC_FILES := $(shell env ANDROID_GNU_X86_TOOLCHAIN=$(ANDROID_GNU_X86_TOOLCHAIN) $(TARGET_ICC) -m32 -print-file-name=libsvml.so)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_SYSTEM_SHARED_LIBRARIES :=
LOCAL_MODULE := libirng
LOCAL_MODULE_SUFFIX:=.so
LOCAL_STRIP_MODULE:=true
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_SRC_FILES := $(shell env ANDROID_GNU_X86_TOOLCHAIN=$(ANDROID_GNU_X86_TOOLCHAIN) $(TARGET_ICC) -m32 -print-file-name=libirng.so)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libimf_s
LOCAL_MODULE_SUFFIX:=.a
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := STATIC_LIBRARIES
LOCAL_SRC_FILES := $(shell env ANDROID_GNU_X86_TOOLCHAIN=$(ANDROID_GNU_X86_TOOLCHAIN) $(TARGET_ICC) -m32 -print-file-name=libimf.a)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libipgo
LOCAL_MODULE_SUFFIX:=.a
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := STATIC_LIBRARIES
LOCAL_SRC_FILES := $(shell env ANDROID_GNU_X86_TOOLCHAIN=$(ANDROID_GNU_X86_TOOLCHAIN) $(TARGET_ICC) -m32 -print-file-name=libipgo.a)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libirng_s
LOCAL_MODULE_SUFFIX:=.a
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := STATIC_LIBRARIES
LOCAL_SRC_FILES := $(shell env ANDROID_GNU_X86_TOOLCHAIN=$(ANDROID_GNU_X86_TOOLCHAIN) $(TARGET_ICC) -m32 -print-file-name=libirng.a)
include $(BUILD_PREBUILT)
endif
endif
